# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Anzeigename'),
        ),
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(default='#55AAFF', max_length=7, verbose_name='Farbe'),
        ),
    ]
