# Generated by Django 4.2 – Desktop-Logik: Groups, Task-Felder, Comments

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copy_deadline_to_due_date(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    for task in Task.objects.all():
        if hasattr(task, 'deadline') and task.deadline:
            task.due_date = task.deadline
            task.save(update_fields=['due_date'])


def status_to_new_choices(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    # in_progress -> open (Desktop hat open, urgent, pause, done)
    Task.objects.filter(status='in_progress').update(status='open')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('color', models.CharField(default='#888888', max_length=7, verbose_name='Farbe')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tasks.group', verbose_name='Übergruppe')),
            ],
            options={
                'verbose_name': 'Gruppe',
                'verbose_name_plural': 'Gruppen',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fällig am'),
        ),
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Fortschritt %'),
        ),
        migrations.AddField(
            model_name='task',
            name='urgent',
            field=models.BooleanField(default=False, verbose_name='Dringend'),
        ),
        migrations.AddField(
            model_name='task',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Geändert von'),
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.group', verbose_name='Gruppe'),
        ),
        migrations.RunPython(copy_deadline_to_due_date, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(
                choices=[('urgent', 'Dringend'), ('open', 'Offen'), ('pause', 'Pausiert'), ('done', 'Erledigt')],
                default='open',
                max_length=20,
                verbose_name='Status',
            ),
        ),
        migrations.RunPython(status_to_new_choices, migrations.RunPython.noop),
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesen an'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Inhalt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Kommentar',
                'verbose_name_plural': 'Kommentare',
                'ordering': ['-created_at'],
            },
        ),
    ]
